import random

REAL_AGENCIES = [
    "Columbus Police Department,OH",
    "Austin Police Department,TX",
    "New York City Police Department,NY",
    "Mesa Police Department,AZ",
    "Cobb County Police Department,GA",
    "Cleveland Division of Police,OH",
    "El Paso Police Department,TX",
    "Chicago Police Department,IL",
    "Scottsdale Police Department,AZ",
    "El Paso Police Department,TX",
    "Dallas County Sheriff's Department,TX",
    "Scottsdale Police Department,AZ",
    "Atlanta Police Department,GA",
    "Tucson Police Department,AZ",
    "Tucson Police Department,AZ",
    "Suffolk County Police Department,NY",
    "Nassau County Sheriff's Department,NY",
    "Naperville Police Department,IL",
    "Cobb County Police Department,GA",
    "Denver Police Department,CO",
    "Jacksonville Sheriff's Office,FL",
    "Cincinnati Police Department,OH",
    "Sacramento Police Department,CA",
    "Lake County Sheriff's Office,IL",
    "New York City Police Department,NY",
    "Tucson Police Department,AZ",
    "Peoria Police Department,IL",
    "Chicago Police Department,IL",
    "Columbus Police Department,OH",
    "New York City Police Department,NY",
    "Maricopa County Sheriff's Office,AZ",
    "Toledo Police Department,OH",
    "Fulton County Sheriff's Office,GA",
    "Tacoma Police Department,WA",
    "Atlanta Police Department,GA",
    "Buffalo Police Department,NY",
    "San Diego County Sheriff's Department,CA",
    "Miami-Dade Police Department,FL",
    "Mesa Police Department,AZ",
    "Dallas County Sheriff's Department,TX",
    "El Paso Police Department,TX",
    "Sacramento Police Department,CA",
    "Scottsdale Police Department,AZ",
    "El Paso Police Department,TX",
    "Columbus Police Department,OH",
    "Cleveland Division of Police,OH",
    "Savannah Police Department,GA",
    "Los Angeles Police Department,CA",
    "Buffalo Police Department,NY",
    "Savannah Police Department,GA",
    "Aurora Police Department,CO",
    "Savannah Police Department,GA",
    "Toledo Police Department,OH",
    "Tacoma Police Department,WA",
    "El Paso Police Department,TX",
    "Lake County Sheriff's Office,IL",
    "Maricopa County Sheriff's Office,AZ",
    "Toledo Police Department,OH",
    "Houston Police Department,TX",
    "Gwinnett County Police Department,GA",
    "Franklin County Sheriff's Office,OH",
    "Los Angeles Police Department,CA",
    "Columbus Police Department,OH",
    "Gwinnett County Police Department,GA",
    "Orlando Police Department,FL",
    "Seattle Police Department,WA",
    "Denver Police Department,CO",
    "Austin Police Department,TX",
    "Fort Worth Police Department,TX",
    "Austin Police Department,TX",
    "Jacksonville Sheriff's Office,FL",
    "Chicago Police Department,IL",
    "Sacramento Police Department,CA",
    "Boulder Police Department,CO",
    "Tucson Police Department,AZ",
    "Gwinnett County Police Department,GA",
    "Phoenix Police Department,AZ",
    "El Paso Police Department,TX",
    "Rochester Police Department,NY",
    "Seattle Police Department,WA",
    "Fulton County Sheriff's Office,GA",
    "Buffalo Police Department,NY",
    "Seattle Police Department,WA",
    "Suffolk County Police Department,NY",
    "Franklin County Sheriff's Office,OH",
    "Miami-Dade Police Department,FL",
    "San Diego County Sheriff's Department,CA",
    "Dallas County Sheriff's Department,TX",
    "Cincinnati Police Department,OH",
    "Buffalo Police Department,NY",
    "Miami-Dade Police Department,FL",
    "Miami-Dade Police Department,FL",
    "San Francisco Police Department,CA",
    "El Paso Police Department,TX",
    "Cobb County Police Department,GA",
    "Dallas County Sheriff's Department,TX",
    "Aurora Police Department,CO",
    "Cleveland Division of Police,OH",
    "Dallas County Sheriff's Department,TX",
    "Franklin County Sheriff's Office,OH",
    "Houston Police Department,TX",
    "Cincinnati Police Department,OH",
    "Cleveland Division of Police,OH",
    "Springfield Police Department,IL",
    "Tampa Police Department,FL",
    "Cleveland Division of Police,OH",
    "Jefferson County Sheriff's Office,CO",
    "Chicago Police Department,IL",
    "Suffolk County Police Department,NY",
    "San Francisco Police Department,CA",
    "Miami-Dade Police Department,FL",
    "Maricopa County Sheriff's Office,AZ",
    "Cincinnati Police Department,OH",
    "Boulder Police Department,CO",
    "Cincinnati Police Department,OH",
    "Nassau County Sheriff's Department,NY",
    "El Paso Police Department,TX",
    "Chicago Police Department,IL",
    "Miami-Dade Police Department,FL",
    "Sacramento Police Department,CA",
    "Sacramento Police Department,CA",
    "Dallas County Sheriff's Department,TX",
    "Toledo Police Department,OH",
    "Savannah Police Department,GA",
    "Buffalo Police Department,NY",
    "Seattle Police Department,WA",
    "Franklin County Sheriff's Office,OH",
    "Jefferson County Sheriff's Office,CO",
    "Fort Worth Police Department,TX",
    "Cobb County Police Department,GA",
    "Los Angeles Police Department,CA",
    "Toledo Police Department,OH",
    "Columbus Police Department,OH",
    "Suffolk County Police Department,NY",
    "Cincinnati Police Department,OH",
    "Gwinnett County Police Department,GA",
    "Columbus Police Department,OH",
    "Boulder Police Department,CO",
    "Colorado Springs Police Department,CO",
    "Rochester Police Department,NY",
    "Columbus Police Department,OH",
    "Lake County Sheriff's Office,IL",
    "Maricopa County Sheriff's Office,AZ",
    "Boulder Police Department,CO",
    "Fulton County Sheriff's Office,GA",
    "Vancouver Police Department,WA",
    "Atlanta Police Department,GA",
    "Aurora Police Department,CO",
    "Dallas County Sheriff's Department,TX",
    "Tacoma Police Department,WA"
    ]


def get_random_agency():
    return random.choice(REAL_AGENCIES)
